test:
  image: wordpress
  script:
  - sh  -c 'if find . -name "*.php" ! -path "./vendor/*" -exec php -l {} 2>&1 \; | grep "syntax error, unexpected"; then exit 1; fi'

build:
   image: docker:latest
   stage: build
   script: 
        - echo "DOCKER_OPTS='--insecure-registry 104.210.155.64:5500'" >> /etc/default/docker
        - echo "DOCKER_OPTS='--insecure-registry 104.210.155.64:5500'" >> /etc/sysconfig/docker
        - docker login  -u 73BD21A749CACCA42DDE -p kTktKzGtthueDYqXDdtYkNdT5aDE8xPfNnXJcheU 104.210.155.64:5500
        - docker build -t 104.210.155.64:5500/root/wordpress .
        - docker push 104.210.155.64:5500/root/wordpress

homolog:
    image: ixis/rancher-compose
    variables:
        RANCHER_URL: http://104.210.155.64:8080/
    stage: deploy
    script: 
        - rancher-compose --url http://104.210.155.64:8080/ --access-key 73BD21A749CACCA42DDE --secret-key kTktKzGtthueDYqXDdtYkNdT5aDE8xPfNnXJcheU -p feed-site -f docker-compose-homolog.yml up --upgrade -d
    environment: homolog