wordpress:
  image: 104.210.155.64:5500/root/wordpress
  restart: always
  links:
    - db
  ports:
    - 8084:80
  volumes: 
    - /srv/feed/site/wordpress/wp-content:/var/www/html/wp-content
  environment: 
    WORDPRESS_DB_HOST: db:3306
    WORDPRESS_DB_PASSWORD: wordpress

db:
  image: mysql:5.7
  ports:
    - 3307:3306
  volumes:
    - "/srv/feed/site/mysql:/var/lib/mysql"
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: wordpress
    MYSQL_DATABASE: wordpress
    MYSQL_USER: wordpress
    MYSQL_PASSWORD: wordpress
